ns1:
  py_test:
    ros__parameters:
      bool_value: True
      int_number: 5
      float_number: 3.14
      str_text: "hi"
      bool_array: [True, False, False]
      int_array: [1, 2, 3]
      float_array: [3.15, 12.2, 6.2]
      str_array: ["a", "b", "c"]
      bytes_array: [0x01, 0xF1]
      nested_param:
        another_int: 3